### ISSUE TITLE
FrameRate parameters

### ISSUE THREAD

**Issue by andriilitvynchuk** [Fonbet/argus-tensor-stream#20]
Hi! Thanks for your great library! I have a question about `FrameRate` parameters: what is the difference between `FrameRate.NATIVE` and `FrameRate.NATIVE_SIMPLE` for local video files and streams? For stream `FrameRate.NATIVE` will not it be equivalent to `FrameRate.FAST`?

**Comment by BykadorovR** [comment]
Hi @litvinich,
In case of NATIVE tensor-stream synchronizes with bitstream timings (pts/dts) so decoding frame time can be different for different frames (be less than frame rate or bigger), but latency is minimal. In case of NATIVE_SIMPLE tensor-stream takes frame rate and determine sleep time depending on decoding time of current frame and frame rate, so delay is constant but latency is growing (because we don't sync with bitstream), so this mode shouldn't be used in low-latency scenarios (when tensor-stream result should be aligned with source stream, like RTMP). FAST is mode without any syncs so tensor-stream reads input as fast as it can (in case of RTMP latency will be minimal, but delay between frames will be dramatically huge)

**Comment by andriilitvynchuk** [comment]
Thanks, that's clear now.
