### ISSUE TITLE
Getting stuck when calling reader.stop()

### ISSUE THREAD

**Issue by jexio** [Fonbet/argus-tensor-stream#37]
Hello. I've tried to decode rtst stream using `simple.py` script from the examples folder and got the following error                                        
```
TID: 140371367552576 Error status != 0, status: -22
TID: 140371367552576 src/Parser.cpp Analyze 162
```
Could you explain why it happens and how to solve it?
I use RTX A4000, Driver Version: 530.30.02    CUDA Version: 12.1

**Comment by BykadorovR** [comment]
Hey, try to disable analyze stage, it's not mandatory.
C++ https://github.com/osai-ai/tensor-stream/blob/ba0df3cdf278d9174ee93a97023bd92887a0a7e9/c_examples/src/Sample.cpp#L61
Python https://github.com/osai-ai/tensor-stream/blob/ba0df3cdf278d9174ee93a97023bd92887a0a7e9/python_examples/simple.py#L99
BTW, looks like you have some issues with FFmpeg because crash happens inside av_bsf_init function call. Make sure you are using FFmpeg 6.0+, you can find suggested environment in Dockerfile: https://github.com/osai-ai/tensor-stream/blob/master/Dockerfile

**Comment by jexio** [comment]
@BykadorovR I'm already using the Dockerfile from repo. `reader.skip_analyze()` works. Thanks!
